# Generated by Django 5.2.8 on 2025-11-12 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('standard', 'Стандарт'), ('comfort', 'Комфорт'), ('business', 'Бизнес')], default='standard', max_length=20, verbose_name='Категория номера')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('name', models.CharField(max_length=100, verbose_name='Название класса')),
            ],
            options={
                'verbose_name': 'Класс номера',
                'verbose_name_plural': 'Классы номеров',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('father_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('mail', models.EmailField(max_length=100, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name', 'last_name', 'father_name'],
                'indexes': [models.Index(fields=['name'], name='vadim_clien_name_ee5a40_idx'), models.Index(fields=['last_name'], name='vadim_clien_last_na_ed9987_idx')],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('flight_time', models.TimeField(verbose_name='Время в пути')),
            ],
            options={
                'verbose_name': 'Перелет',
                'verbose_name_plural': 'Перелеты',
                'ordering': ['date', 'price'],
                'indexes': [models.Index(fields=['date'], name='vadim_fligh_date_82335d_idx'), models.Index(fields=['flight_time'], name='vadim_fligh_flight__f3573c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('place', models.TextField(verbose_name='Местоположение')),
                ('room_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='vadim.roomclass', verbose_name='Класс Номера')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тура')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vadim.flight', verbose_name='Перелет')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vadim.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
                'ordering': ['name', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vadim.client', verbose_name='клиент')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vadim.tour', verbose_name='тур')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['place'], name='vadim_hotel_place_21a6a7_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['room_class'], name='vadim_hotel_room_cl_273b85_idx'),
        ),
    ]
