# Generated by Django 5.2.8 on 2025-11-12 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vadim', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomclass',
            name='name',
        ),
    ]
