# Generated by Django 5.2.8 on 2025-11-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vadim', '0002_remove_roomclass_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_url',
            field=models.URLField(blank=True, null=True, verbose_name='Отель'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_url',
            field=models.URLField(blank=True, null=True, verbose_name='Тур'),
        ),
    ]
