# Generated by Django 5.2.7 on 2025-11-05 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vadim', '0002_chance'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='chance',
            name='cases',
        ),
        migrations.RemoveField(
            model_name='chance',
            name='item',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='item',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='user',
        ),
        migrations.RemoveField(
            model_name='upgrade',
            name='item',
        ),
        migrations.RemoveField(
            model_name='upgrade',
            name='user',
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('father_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('mail', models.EmailField(max_length=100, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name', 'last_name', 'father_name'],
                'indexes': [models.Index(fields=['name'], name='vadim_clien_name_ee5a40_idx'), models.Index(fields=['last_name'], name='vadim_clien_last_na_ed9987_idx')],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('flight_time', models.TimeField(verbose_name='Время в пути')),
            ],
            options={
                'verbose_name': 'Перелет',
                'verbose_name_plural': 'Перелеты',
                'ordering': ['date', 'price'],
                'indexes': [models.Index(fields=['date'], name='vadim_fligh_date_82335d_idx'), models.Index(fields=['flight_time'], name='vadim_fligh_flight__f3573c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('place', models.TextField(verbose_name='Местоположение')),
                ('star_rating', models.IntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], default=3, verbose_name='Количество звезд')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['place'], name='vadim_hotel_place_21a6a7_idx'), models.Index(fields=['star_rating'], name='vadim_hotel_star_ra_a42789_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тура')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vadim.flight', verbose_name='Перелет')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vadim.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
                'ordering': ['name', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vadim.client', verbose_name='клиент')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vadim.tour', verbose_name='тур')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.DeleteModel(
            name='case_contents',
        ),
        migrations.DeleteModel(
            name='Cases',
        ),
        migrations.DeleteModel(
            name='Chance',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='Upgrade',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
