# Generated by Django 5.2.8 on 2025-11-27 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vadim', '0003_hotel_hotel_url_tour_tour_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['date'], 'verbose_name': 'Перелет', 'verbose_name_plural': 'Перелеты'},
        ),
        migrations.RemoveField(
            model_name='flight',
            name='price',
        ),
    ]
